/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[id]': typeof import('./src/pages/updateauthor/[id].vue')['default']
    Addauthor: typeof import('./src/pages/addauthor/index.vue')['default']
    AddAuthor: typeof import('./src/components/AddAuthor.vue')['default']
    AddAuthorView: typeof import("./src/views/AddAuthorView.vue")["default"]
    App: typeof import("./src/App.vue")["default"]
    AuthorModal: typeof import('./src/components/AuthorModal.vue')['default']
    Authors: typeof import('./src/store/authors.ts')['default']
    createRouter: typeof import("vue-router")["createRouter"]
    CreateRouter: typeof import("vue-router")["CreateRouter"]
    DeleteAuthors: typeof import('./src/components/DeleteAuthors.vue')['default']
    DisplayAuthors: typeof import('./src/components/DisplayAuthors.vue')['default']
    HomeView: typeof import("./src/views/HomeView.vue")["default"]
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Types: typeof import("./src/types/types.ts")["default"]
    UpdateAuthor: typeof import('./src/components/UpdateAuthor.vue')['default']
  }
}
